---
abstract: "optimize path finding searches for a large\nset of initial conditions (for better average performance)."
author:
  - 'Shlomi Fish <shlomif@cpan.org>'
build_requires:
  File::Spec: 0
  File::Temp: 0
  IO::Handle: 0
  IPC::Open3: 0
  Module::Build: 0.3601
  Test::Differences: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.009, CPAN::Meta::Converter version 2.132830'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AI-Pathfinding-OptimizeMultiple
requires:
  Carp: 0
  Exception::Class: 0
  File::Path: 0
  Getopt::Long: 0
  IO::File: 0
  IO::Handle: 0
  MooX: 0
  MooX::Types::MooseLike::Base: 0
  MooX::late: 0.007
  PDL: 0
  PDL::IO::FastRaw: 0
  strict: 0
  vars: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=AI-Pathfinding-OptimizeMultiple
  repository: ssh://hg@bitbucket.org/shlomif/fc-solve
version: 0.0.6
